version: '3.8'

services:
  mysql:
    # Версия СУБД mysql - 8.0.41
    image: mysql:8.0.41
    # Перезапуск системы в случях сбоев, параметр необходим для стабильного доступа к mysql
    restart: always
    ports:
      # Порт на котором работает mysql - 3306
      # Перенаправление (переадресация) портов называется порт маппинг
      - '3306:3306'
    volumes:
      # даная строка применяется для указания пути, куда будут импортироваться файлы из БД
      # внутри контейнера /var/lib/mysql в локальную папку на ПК "./data"
      - ./data:/var/lib/mysql
    environment:
      # Переменная среды устанавливает случайный пароль для учетной записи root.
      # Значение yes указывает контейнеру создать автоматически сгенерированный безопасный пароль для администратора базы данных.
      # Пароль выводится в логах Docker, и вам потребуется скопировать его оттуда для дальнейшего использования.
      # Root-пользователь обладает максимальными полномочиями для управления системой MySQL, включая управление пользователями,
      # созданием и удалением баз данных, изменением настроек сервера и восстановление данных.
      # Данная переменная необходима для безопасности.
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      # Переменная создает базу данных с именем app, которую сразу же можно использовать приложением.
      # Это удобно, поскольку база данных создается автоматически при запуске контейнера.
      - MYSQL_DATABASE=app
      # Создается новая учётная запись с именем пользователя app.
      # Этот пользователь будет иметь доступ к указанной ранее базе данных app.
      - MYSQL_USER=app
      # Устанавливается пароль для пользователя app. В данном примере используется простой пароль pass,
      # однако рекомендуется использовать более сложный и защищённый пароль в реальных проектах.
      - MYSQL_PASSWORD=pass

  postgres:
    image: postgres:14-alpine
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgres
    environment:
      POSTGRES_DB: app
      POSTGRES_USER: app
      POSTGRES_PASSWORD: pass

  gate-simulator:
    # Путь к папке с Dockerfile
    build: ./gate-simulator
    # Используем порт 9999, указанный в Dockerfile
    ports:
      - "9999:9999"
